# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [16]:
import numpy as np
np.__version__

'1.21.5'

2) Создать нулевой вектор размера 10

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [18]:
np.full(7, 7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [19]:
np.arange(10, 101, 2)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [20]:
array = np.random.rand(10)
reversed_array = array[::-1]

print(array)
reversed_array

[0.59369247 0.88711269 0.64246995 0.8727295  0.19613221 0.33580289
 0.45561961 0.44954733 0.494997   0.365975  ]


array([0.365975  , 0.494997  , 0.44954733, 0.45561961, 0.33580289,
       0.19613221, 0.8727295 , 0.64246995, 0.88711269, 0.59369247])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [21]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [22]:
matrix = np.zeros((4, 4))
np.fill_diagonal(matrix[:-1, 1:], 1)
matrix

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [23]:
matrix2 = np.full((4, 4), 7)
np.fill_diagonal(matrix2, np.arange(1, 5))
matrix2

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [24]:
matrix3 = np.tile(np.arange(5), (5, 1))
matrix3

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [25]:
matrix4 = np.random.rand(10, 10)
matrix4 = matrix4 - matrix4.mean(axis=1)
matrix4

array([[ 4.38842610e-01, -7.19544031e-01,  3.68619045e-01,
        -3.73782213e-01, -3.32270785e-01, -2.82755392e-01,
         1.62304110e-01,  1.57840381e-01,  1.59502047e-01,
        -3.18915313e-01],
       [ 3.23516535e-01,  1.20761382e-01, -2.57419754e-01,
         3.08276982e-01,  4.85366789e-01,  3.82869228e-01,
         6.83447553e-01,  6.09225677e-01, -7.87323044e-02,
        -5.33456778e-03],
       [ 4.34437578e-01, -2.81374278e-01, -2.78319534e-01,
        -3.76398248e-01,  1.42079339e-01, -3.91722951e-01,
        -1.08377258e-01,  5.45208247e-01, -3.76754807e-01,
        -3.24477536e-01],
       [-4.09688264e-02, -1.35538183e-01, -7.89214756e-02,
         3.11538811e-01,  6.83700347e-02, -1.07488094e-01,
         2.77169089e-01, -1.55167616e-01,  1.44822158e-01,
         2.97872218e-01],
       [ 2.16741744e-01, -5.99336312e-01,  4.10742343e-03,
        -1.67106367e-01,  1.46385568e-01,  5.51185141e-02,
         3.51839608e-01,  5.29431785e-02, -6.76670709e-02,
         2.

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [26]:
import numpy as np
matrix5 = np.random.rand(10, 10)
medians = np.median(matrix5, axis=0)
matrix5 = matrix5 - medians
matrix5

array([[ 0.27274366, -0.11109519,  0.70867824,  0.19935846, -0.27048415,
        -0.36549629,  0.20145341,  0.47478885,  0.05042432,  0.29096896],
       [-0.16185712,  0.01985867, -0.14038139, -0.08213836, -0.11717393,
        -0.24171473,  0.19723312, -0.40278854, -0.21213001, -0.45150897],
       [-0.04503482, -0.01985867,  0.76316857, -0.30980555, -0.15476642,
        -0.18746504, -0.30956261, -0.31946968,  0.61442375,  0.52169791],
       [-0.16504823, -0.16917609,  0.00877672, -0.08883569,  0.11718171,
        -0.00102461,  0.24919563,  0.37234587, -0.05042432,  0.19345873],
       [-0.01351036,  0.42157339, -0.09010891, -0.21358267,  0.10036571,
         0.15763222, -0.04701686,  0.29852972,  0.08248476, -0.42535411],
       [-0.30839245,  0.30918683, -0.08621765,  0.22913733,  0.01088487,
         0.25950666,  0.04701686, -0.29849744,  0.26573528,  0.07432497],
       [ 0.01351036,  0.02880177,  0.08696774,  0.08213836, -0.01088487,
         0.03963484, -0.19296059, -0.36658095

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [27]:
matrix6 = np.random.rand(5, 5)
maxs = np.max(matrix6, axis=1).reshape(-1, 1)
mins = np.min(matrix6, axis=1).reshape(-1, 1)
matrix6 = np.hstack((matrix6, maxs, mins))
matrix6

array([[0.89419444, 0.54848509, 0.79825803, 0.52353184, 0.34359958,
        0.89419444, 0.34359958],
       [0.03478716, 0.06827383, 0.27046068, 0.66329982, 0.50327614,
        0.66329982, 0.03478716],
       [0.38325506, 0.25338386, 0.39735452, 0.69473935, 0.37152585,
        0.69473935, 0.25338386],
       [0.5200755 , 0.32244715, 0.37434492, 0.39976159, 0.00821445,
        0.5200755 , 0.00821445],
       [0.830671  , 0.94448576, 0.60813021, 0.25172543, 0.28251882,
        0.94448576, 0.25172543]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [28]:
odd_vector = np.arange(1, 51, 2)
even_vector = np.arange(2, 52, 2)

odd_matrix = odd_vector.reshape(5, 5)
even_matrix = even_vector.reshape(5, 5)

product = np.dot(odd_matrix, even_matrix)

inverse = np.linalg.inv(product)

inverse, product

(array([[-6.21359223e-02, -4.73786408e-02, -7.33007752e+11,
          1.46601550e+12, -7.33007752e+11],
        [ 8.94517934e+12, -2.38538116e+12, -1.75921860e+13,
          6.55979819e+12,  4.47258967e+12],
        [-1.31195964e+13, -7.15614348e+13,  1.77387876e+14,
         -8.76130621e+13, -5.09378268e+12],
        [-5.96345290e+11,  1.50279013e+14, -2.99067163e+14,
          1.49682668e+14, -2.98172645e+11],
        [ 4.77076232e+12, -7.63321971e+13,  1.40004481e+14,
         -7.00954193e+13,  1.65237341e+12]]),
 array([[ 750,  800,  850,  900,  950],
        [1850, 2000, 2150, 2300, 2450],
        [2950, 3200, 3450, 3700, 3950],
        [4050, 4400, 4750, 5100, 5450],
        [5150, 5600, 6050, 6500, 6950]]))

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [29]:
matrix7 = np.zeros((8,8))
matrix7[1::2, ::2] = 1
matrix7[::2, 1::2] = 1
matrix7

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])